# Generated by Django 4.2.7 on 2023-12-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_produit', models.IntegerField()),
                ('nom', models.CharField(max_length=40)),
            ],
        ),
    ]
